---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - lib/eac_active_scaffold/patches/action_dispatch.rb
  - lib/eac_active_scaffold/rspec/shared_contexts/active_scaffold_controller.rb
  - spec/rubocop_check_spec.rb
  - spec/spec_helper.rb
